config/routes.rb
#Последний Листинг :8.1 :8.49: Обработка флажка “remember me”. app/controllers/#sessions_controller.rb  
#Листинг 3.37 :11.29 :12.20
Rails.application.routes.draw do
   
 root 'static_pages#home'  #root 'application#hello'   #root 'application#hello_world   #root 'hello_world#home' 
 get 'sessions/new'
#Листинг 8.1
 get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get 'password_resets/new'
  get 'password_resets/edit'
# 11.29
 resources :microposts,          only: [:create, :destroy]
#Листинг 10.1: Добавление ресурса для активаций аккаунта. config/routes.rb :11.29
resources :account_activations, only: [:edit]
resources :password_resets,     only: [:new, :create, :edit, :update]

resources :relationships,       only: [:create, :destroy]
#12.15
resources :users do 
    member do
      get :following, :followers
    end
  end
  resources :students
resources :allstudents

 #/home/sf/libr/config      Aug30   
#root 'users#index'
#/Aug30
 
#get 'articles/index'
get 'articles' => 'articles#index'

#get 'static_pages/home'
 # get 'static_pages/help'
  #get 'static_pages/about'
  #get 'static_pages/users'
  #get 'static_pages/referatHartl'
#get 'studall' => 'students#allstudents'
get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
get 'signup'  => 'users#new'  #Листинг 5.33:Маршрут для страницы регистрации. config/#routes.rb Листинг 7.3:
                  #get 'users'  => 'static_pages#users'

# sept 10 get 'sessions/new'
 # get 'static_pages/usersallowed'
 #get "/static_pages/users"
  # Sept01  get 'sessions/new'
#Листинг 5.22: Маршруты для статических страниц. config/routes.rb Листинг 7.3:
 #Articles Articles_path
#get 'Articles'    => '/articles'



resources :articles
  resources :folders
  resources :reports





#Листинг 5.33: Маршрут для страницы регистрации. config/routes.rb 
 # ! devise_for :users
 # ! devise_for :admin_users, ActiveAdmin::Devise.config
 #ActiveAdmin.routes(self)
  #  root 'users#show' был  у Мелаш
  # Example of regular route:
  get 'attach_files' => 'migration#attach_files'
  post 'attach_files' => 'migration#attach_files_action'

  post 'api/reviews_by_chapter' => 'categories#reviews_by_chapter'
  post 'api/sections_by_review' => 'categories#sections_by_review'
  post 'api/subsections_by_section' => 'categories#subsections_by_section'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
 

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable


  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
#Листинг :6.39 8.31 8.33: Добавление метода authenticated? к модели User. app/models/user.rb #Листинг 8.18: :8.32 :8.38 :9.10 :10.3
#Листинг 10.33: Добавление методов активации пользователя в модель User. app/models/user.rb  :11.10 :11.18  :12.8 :12.10, :12.12 :10.33 :12.43 :12.45 :12.46

class User < ActiveRecord::Base
#11.10 :11.18 Листинг 11.44: Предварительная реализация потока микросообщений. app/models/user.rb 
  has_many :microposts, dependent: :destroy
   has_many :students, dependent: :destroy

#12.12
has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
#12.8
has_many :following, through: :active_relationships, source: :followed
has_many :followers, through: :passive_relationships, source: :follower
# :10.3
 attr_accessor :remember_token, :activation_token
  before_save   :downcase_email
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_nil: true


  # Возвращает дайджест данной строки
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
# Возвращает случайный токен
  def User.new_token
    SecureRandom.urlsafe_base64
  end
 # :8.32 Запоминает пользователя в базе данных для использования в постоянной сессии.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
# Возвращает true, если предоставленный токен совпадает с дайджестом.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
#Листинг 8.31: Добавление метода для генерации токена. app/models/user.rb 
#Листинг 8.33: Добавление метода authenticated? к модели User. app/models/user.rb 
def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
#Листинг 8.38: Добавление метода forget к модели User. app/models/user.rb 

# Забывает пользователя
def forget
    update_attribute(:remember_digest, nil)
  end
# :10.3 :10.33

  # Активирует аккаунт.
def activate
    update_attribute(:activated,    true)
    update_attribute(:activated_at, Time.zone.now)
  end

  # Отправляет электронное письмо для активации. user.rb :10.33
  def send_activation_email
#UserMailer.account_activation(self).deliver_now    
UserMailer.account_activation(self).deliver
  end
# Определяет прото-ленту.
  # Полная реализация в "Следовании за пользователями".
 #def feed
 #   Micropost.where("user_id = ?", id)
 # end 
# Начать читать сообщения пользователя.
  
#Oct_22 
def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # :12.10 Служебные методы ...Oct_22  Перестать читать сообщения пользователя.
  def unfollow(other_user)
   active_relationships.find_by(followed_id: other_user.id).destroy
  end
 # Возвращает true, если текущий пользователь читает сообщения другого пользователя.
  def following?(other_user)
    following.include?(other_user)
  end
 # Возвращает true, если истек срок годности сброса пароля.
  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  # Возвращает ленту сообщений пользователя.
  def feed
#11.44
#Micropost.where("user_id = ?", id)
# 12.43    Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
#Micropost.where("user_id IN (?) OR user_id = ?", following_ids, id)
   #Oct22 following_ids = "SELECT followed_id FROM relationships
    #Oct_22                 WHERE  follower_id = :user_id"
#12.45   
#Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
 #                   following_ids: following_id, user_id: id)
#following_ids = "SELECT followed_id FROM relationships
 #                    WHERE  follower_id = :user_id"
# Micropost.where("user_id IN (:following_ids) OR user_id = :user_id",
 #                   following_ids: following_ids, user_id: id)
# :12.46
following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

# :12.10
  # Начинает читать сообщения пользователя..
 def follow(other_user)
 active_relationships.create(followed_id: other_user.id)
  end
# 12.10 Перестать читать сообщения пользователя.
 def unfollow(other_user)
  active_relationships.find_by(followed_id: other_user.id).destroy
end
# Возвращает true, если текущий пользователь читает сообщения другого пользователя.
  def following?(other_user)
    following.include?(other_user)
  end
                                         private

    # Переводит адрес электронной почты в нижний регистр.
    def downcase_email
      self.email = email.downcase
    end

    # Создает и присваивает активационнй токен и дайджест.
    def create_activation_digest
      self.activation_token  = User.new_token
      #self.activation_digest = User.digest(activation_token)
    end
end

app/controllers/users_controller.rb
#Листинг :7.5 :7.12 :7.17 :7.18 :7.23 :8.22: Вход пользователя после регистрации. app/controllers/users_controller.rb !! :9.12 9.28: :9.32  :9.33
#Листинг 9.1: Действие edit. app/controllers/users_controller.rb :9.53 :11.22 :9.53 :12.25 :9.32:9.53 :9.54

class UsersController < ApplicationController
#12.25
before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]
  before_action :correct_user,   only: [:edit, :update]
before_action :admin_user, only: :destroy

def index
#@users = User.all
  @users = User.paginate(page: params[:page])      
  end

def show
    @user = User.find(params[:id])
@microposts = @user.microposts.paginate(page: params[:page])
#Oct_19 @student = Student.find(params[:id])
  end
# :9.25
#before_action :logged_in_user, only: [:edit, :update]
 # before_action :correct_user,   only: [:edit, :update]
  def edit
    @user = User.find(params[:id])
  end

def update
@user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end

  def new
    @user = User.new
  end
#Листинг 10.21: Добавление активации аккаунта к регистрации пользователя. КРАСНЫЙ app/controllers/users_controller.rb 
# :10.34 Sept 26Листинг 11.22: Добавление переменной экземпляра @microposts к действию show. app/controllers/users_controller.r
 #8.22
def create
   @user = User.new(user_params)
      if @user.save
         log_in @user

          @user.send_activation_email

           flash[:info] = "Sept26 Please check your email to activate your account."
           redirect_to root_url

          
           #flash[:success] = "Welcome to the Sample App!"
           #redirect_to @user
         else
           render 'new'
    end
  end

def following
    @title = "Oct25Following in/users_controller for Show_follow"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page]) 
    render 'show_follow'
  end
# :12.25 
  def followers
    @title = "Oct25indef_followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
    end
# Предфильтры

    # Подтверждает вход пользователяВспомним из Раздела 9.2.1, что требование входа обеспечивает предфильтр с методом logged_in_user (Листинг 9.12). В то время он был нужен только в контроллере Users, но теперь в нем появилась необходимость и в контроллере Microposts, поэтому мы переместим его в контроллер Application, который является базовым классом для всех контроллеров (Раздел 4.4.4). Результат показан в Листинге 11.31.
#11.31 Удаляем
#11.31    def logged_in_user
 #11.31     unless logged_in?
 #11.31          store_location
 #11.31       flash[:danger] = "Please log in."
 #11.31       redirect_to login_url
 #11.31     end


# Подтверждает администратора.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
 
    # Подтверждает правильного пользователя
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
# Листинг 7.8: Представление, показывающее пользователя с именем и граватаром. app/#views/users/show.html.erbSept 01 Листинг 7.9: Определение вспомогательного метода #gravatar_for. app/helpers/users_helper.rb 
module UsersHelper

  # Возвращает граватар для данного пользователя
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/''_index.html.erb
<!--#Листинг :2.5 
def index
    @users = User.all
  end
2.7: Представление index для пользователей. app/views/users/index.html.erb

<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete,
                                     data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to 'New User', new_user_path %>
Листинг 9.34:Листинг 9.41 :9.46 9.47: Листинг 9.48: Полностью реорганизованный список пользователей. #ЗЕЛЕНЫЙ app/views/users/index.html.erb -->

<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>



<%= will_paginate %>

app/views/users/''new.html.erb
<!--#Листинг 5.35: 
#User.new Листинг 7.13: Форма регистрации новых пользователей. app/views/users/#new.html.erbЛистинг 7.18: 
#Листинг 10.33. Обновление рендеринга ошибок регистрации пользователей.:11.41
# -->

<% provide(:title, 'Sign up') %>
<h1>Sign up Sept 16</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages'%>, object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
     <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password %><p><p>

      <%= f.label :password_confirmation, "Password Confirmation" %><p><p>
     <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/''oct19_user.html.erb
<!--#Листинг 9.47: Партиал для отображения отдельно взятого пользователя. app/views/users/_user.html.erb

<li>
  <%#= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
<%= link_to user.name, user %>
</li>

app/views/users/Oct_22_user_info.html.erb
<div class="row" style="margin: 20px 0;">
  <div class="col-xs-12 col-sm-4">
    <%= image_tag(current_user.avatar, class: 'img-responsive img-rounded') %>
  </div>
  <div class="col-xs-12 col-sm-8">
    <form>
      <div class="form-group">
        <label for="exampleInputEmail1">Фамилия</label>
        <%= text_field_tag(:last_name, current_user.last_name, class: 'form-control') %>
      </div>
      <div class="form-group">
        <label for="exampleInputEmail1">Имя</label>
        <%= text_field_tag(:first_name, current_user.first_name, class: 'form-control') %>
      </div>
      <div class="form-group">
        <label for="exampleInputFile">Отчество</label>
        <%= text_field_tag(:patronymic, current_user.patronymic, class: 'form-control') %>
      </div>
    </form>
  </div>
</div>

app/views/users/_follow.html.erb
<!-- #Листинг 12.21: Форма для того, чтобы начать читать сообщения пользователя. app/views/users/_follow.html.erb :12.33  
12.21
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>
-->
#Листинг 12.21: Форма для того, чтобы начать читать сообщения пользователя. app/views/users/_follow.html.erb

<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<!-- #Листинг 12.19: Партиал формы “follow/unfollow (читать/не читать)”. app/views/users/_follow_form.html.erb -->

<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<!-- #Листинг 12.21: Форма для того, чтобы начать читать сообщения пользователя. app/views/users/_follow.html.erb :12.33  
12.21
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

Листинг 12.22: Форма для того, чтобы перестать читать сообщения пользователя. app/views/users/_unfollow.html.erb -->

<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<!--#Листинг 9.47: Партиал для отображения отдельно взятого пользователя. app/views/users/_user.html.erb
Листинг 9.52: Ссылки для удаления пользователей (видны только админам). app/views/users/_user.html.erb -->
<li>
  <%= gravatar_for user %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<!--#Листинг 9.2: Представление для редактирования пользователя app/views/users/#edit.html.erb  :11.42 -->

<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<!--#Листинг 9.41: Список пользователей с пагинацией. app/views/users/index.html.erb  -->
#Листинг 9.48: Полностью реорганизованный список пользователей. ЗЕЛЕНЫЙ app/views/users/index.html.erb

<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<!--#Листинг 5.35: 
#User.new Листинг 7.13: Форма регистрации новых пользователей. app/views/users/#new.html.erbЛистинг 7.18: 
#Листинг 10.33. Обновление рендеринга ошибок регистрации пользователей.:11.41
# -->

<% provide(:title, 'Sign up') %>
<h1>Sign up </h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>


 <%#= f.label :fio %>
<%#no= @user.student.fio %>


      <%#= f.text_field :name, class: 'form-control' %>


 
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
     <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password %><p><p>

      <%= f.label :password_confirmation, "Password Confirmation" %><p><p>
     <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<!--#libr  Sept 01 Листинг :7.4 7.10: Добавление боковой панели к представлению пользователя show. app/views/users/show.html.erb
#Листинг 7.4:Листинг 7.8:Листинг 7.10 Листинг 7.10: Добавление боковой панели к представлению пользователя show. app/views/users/show.html.erb :11.23  :12.23    -->
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
         <section>
           <h1>
             <%= gravatar_for @user %>
             <%= @user.name %>
           </h1>
         </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  
<div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<!-- #Листинг 12.26: Представление show_follow для визуализации читаемых и читателей. app/views/users/show_follow.html.erb -->

<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "Show_myprofileshow_follow", @user %></span>
  <span><b>Microposts:</b> <%= @user.microposts.count %></span>
 </section>
   
<section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>

  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>